# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ezLNT.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ezLNT(object):
    def setupUi(self, ezLNT):
        ezLNT.setObjectName("ezLNT")
        ezLNT.resize(1600, 854)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ezLNT.sizePolicy().hasHeightForWidth())
        ezLNT.setSizePolicy(sizePolicy)
        ezLNT.setMinimumSize(QtCore.QSize(0, 0))
        ezLNT.setMaximumSize(QtCore.QSize(1600, 900))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        ezLNT.setFont(font)
        ezLNT.setStyleSheet("\n"
"font: 25 10pt \"Calibri Light\";")
        ezLNT.setInputMethodHints(QtCore.Qt.ImhNone)
        self.GUI = QtWidgets.QWidget(ezLNT)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.GUI.setFont(font)
        self.GUI.setObjectName("GUI")
        self.layoutWidget = QtWidgets.QWidget(self.GUI)
        self.layoutWidget.setGeometry(QtCore.QRect(1050, 10, 534, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.output_box = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.output_box.setContentsMargins(0, 0, 0, 0)
        self.output_box.setObjectName("output_box")
        self.output_menu = QtWidgets.QHBoxLayout()
        self.output_menu.setObjectName("output_menu")
        self.btnGenLog = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGenLog.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.btnGenLog.setFont(font)
        self.btnGenLog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGenLog.setObjectName("btnGenLog")
        self.output_menu.addWidget(self.btnGenLog)
        self.btnGenClear = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGenClear.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.btnGenClear.setFont(font)
        self.btnGenClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGenClear.setObjectName("btnGenClear")
        self.output_menu.addWidget(self.btnGenClear)
        spacerItem = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.output_menu.addItem(spacerItem)
        self.output_box.addLayout(self.output_menu)
        self.tbOutText = QtWidgets.QPlainTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.tbOutText.setFont(font)
        self.tbOutText.setObjectName("tbOutText")
        self.output_box.addWidget(self.tbOutText)
        self.pbGen = QtWidgets.QProgressBar(self.layoutWidget)
        self.pbGen.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pbGen.setFont(font)
        self.pbGen.setStyleSheet("font: 25 8pt \"Calibri Light\";")
        self.pbGen.setProperty("value", 0)
        self.pbGen.setObjectName("pbGen")
        self.output_box.addWidget(self.pbGen)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.GUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 209, 1031, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tblLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tblLayout.setContentsMargins(0, 0, 0, 0)
        self.tblLayout.setObjectName("tblLayout")
        self.tbCLLog = QtWidgets.QTextBrowser(self.GUI)
        self.tbCLLog.setGeometry(QtCore.QRect(1050, 700, 531, 101))
        self.tbCLLog.setMouseTracking(True)
        self.tbCLLog.setAutoFillBackground(False)
        self.tbCLLog.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.tbCLLog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbCLLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbCLLog.setObjectName("tbCLLog")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.GUI)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 2, 851, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tw = QtWidgets.QTabWidget(self.verticalLayoutWidget_2)
        self.tw.setObjectName("tw")
        self.zigbee = QtWidgets.QWidget()
        self.zigbee.setObjectName("zigbee")
        self.layoutWidget1 = QtWidgets.QWidget(self.zigbee)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 9, 752, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zbShowInfo = QtWidgets.QPushButton(self.layoutWidget1)
        self.zbShowInfo.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.zbShowInfo.setFont(font)
        self.zbShowInfo.setCheckable(False)
        self.zbShowInfo.setObjectName("zbShowInfo")
        self.horizontalLayout_4.addWidget(self.zbShowInfo)
        self.zbToggle = QtWidgets.QPushButton(self.layoutWidget1)
        self.zbToggle.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.zbToggle.setFont(font)
        self.zbToggle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zbToggle.setCheckable(True)
        self.zbToggle.setObjectName("zbToggle")
        self.horizontalLayout_4.addWidget(self.zbToggle)
        self.zbRunScript = QtWidgets.QPushButton(self.layoutWidget1)
        self.zbRunScript.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.zbRunScript.setFont(font)
        self.zbRunScript.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zbRunScript.setCheckable(False)
        self.zbRunScript.setObjectName("zbRunScript")
        self.horizontalLayout_4.addWidget(self.zbRunScript)
        self.zbLoadConfig = QtWidgets.QPushButton(self.layoutWidget1)
        self.zbLoadConfig.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.zbLoadConfig.setFont(font)
        self.zbLoadConfig.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zbLoadConfig.setObjectName("zbLoadConfig")
        self.horizontalLayout_4.addWidget(self.zbLoadConfig)
        self.zbSaveConfig = QtWidgets.QPushButton(self.layoutWidget1)
        self.zbSaveConfig.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.zbSaveConfig.setFont(font)
        self.zbSaveConfig.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zbSaveConfig.setObjectName("zbSaveConfig")
        self.horizontalLayout_4.addWidget(self.zbSaveConfig)
        self.zbProgram = QtWidgets.QPushButton(self.layoutWidget1)
        self.zbProgram.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.zbProgram.setFont(font)
        self.zbProgram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zbProgram.setCheckable(True)
        self.zbProgram.setObjectName("zbProgram")
        self.horizontalLayout_4.addWidget(self.zbProgram)
        self.tw.addTab(self.zigbee, "")
        self.ble_mesh = QtWidgets.QWidget()
        self.ble_mesh.setObjectName("ble_mesh")
        self.layoutWidget2 = QtWidgets.QWidget(self.ble_mesh)
        self.layoutWidget2.setGeometry(QtCore.QRect(13, 10, 811, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.blmToggle = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmToggle.setEnabled(True)
        self.blmToggle.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmToggle.setFont(font)
        self.blmToggle.setCheckable(True)
        self.blmToggle.setObjectName("blmToggle")
        self.horizontalLayout_3.addWidget(self.blmToggle)
        self.blmReset = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmReset.setEnabled(True)
        self.blmReset.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmReset.setFont(font)
        self.blmReset.setObjectName("blmReset")
        self.horizontalLayout_3.addWidget(self.blmReset)
        self.blmFN = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmFN.setEnabled(True)
        self.blmFN.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmFN.setFont(font)
        self.blmFN.setObjectName("blmFN")
        self.horizontalLayout_3.addWidget(self.blmFN)
        self.blmRefresh = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmRefresh.setEnabled(True)
        self.blmRefresh.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmRefresh.setFont(font)
        self.blmRefresh.setCheckable(False)
        self.blmRefresh.setObjectName("blmRefresh")
        self.horizontalLayout_3.addWidget(self.blmRefresh)
        self.blmRunScpt = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmRunScpt.setEnabled(True)
        self.blmRunScpt.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmRunScpt.setFont(font)
        self.blmRunScpt.setObjectName("blmRunScpt")
        self.horizontalLayout_3.addWidget(self.blmRunScpt)
        self.blmProgram = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmProgram.setEnabled(True)
        self.blmProgram.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmProgram.setFont(font)
        self.blmProgram.setObjectName("blmProgram")
        self.horizontalLayout_3.addWidget(self.blmProgram)
        self.blmView = QtWidgets.QPushButton(self.layoutWidget2)
        self.blmView.setEnabled(True)
        self.blmView.setMinimumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.blmView.setFont(font)
        self.blmView.setObjectName("blmView")
        self.horizontalLayout_3.addWidget(self.blmView)
        self.tw.addTab(self.ble_mesh, "")
        self.verticalLayout.addWidget(self.tw)
        self.layoutWidget_3 = QtWidgets.QWidget(self.GUI)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 129, 811, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rbSetServer = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rbSetServer.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.rbSetServer.setFont(font)
        self.rbSetServer.setObjectName("rbSetServer")
        self.buttonGroup = QtWidgets.QButtonGroup(ezLNT)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbSetServer)
        self.horizontalLayout_8.addWidget(self.rbSetServer)
        self.lblServerAddr = QtWidgets.QLabel(self.layoutWidget_3)
        self.lblServerAddr.setMinimumSize(QtCore.QSize(200, 30))
        self.lblServerAddr.setStyleSheet("font: 25 10pt \"Calibri Light\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.lblServerAddr.setText("")
        self.lblServerAddr.setObjectName("lblServerAddr")
        self.horizontalLayout_8.addWidget(self.lblServerAddr)
        self.btnServerSwitch = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btnServerSwitch.setMinimumSize(QtCore.QSize(90, 30))
        self.btnServerSwitch.setStyleSheet("font: 25 8pt \"Calibri Light\";")
        self.btnServerSwitch.setCheckable(True)
        self.btnServerSwitch.setObjectName("btnServerSwitch")
        self.horizontalLayout_8.addWidget(self.btnServerSwitch)
        self.lineServerCmd = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineServerCmd.setMinimumSize(QtCore.QSize(80, 30))
        self.lineServerCmd.setObjectName("lineServerCmd")
        self.horizontalLayout_8.addWidget(self.lineServerCmd)
        self.cbTargetClientAddr = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cbTargetClientAddr.setMinimumSize(QtCore.QSize(225, 30))
        self.cbTargetClientAddr.setStyleSheet("font: 25 9pt \"Calibri Light\";\n"
"background-color: rgb(255, 255, 255);")
        self.cbTargetClientAddr.setObjectName("cbTargetClientAddr")
        self.cbTargetClientAddr.addItem("")
        self.cbTargetClientAddr.addItem("")
        self.horizontalLayout_8.addWidget(self.cbTargetClientAddr)
        self.btnServerSend = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btnServerSend.setMinimumSize(QtCore.QSize(90, 30))
        self.btnServerSend.setStyleSheet("font: 25 8pt \"Calibri Light\";")
        self.btnServerSend.setObjectName("btnServerSend")
        self.horizontalLayout_8.addWidget(self.btnServerSend)
        self.layoutWidget_2 = QtWidgets.QWidget(self.GUI)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 95, 581, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rbSetClient = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbSetClient.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.rbSetClient.setFont(font)
        self.rbSetClient.setObjectName("rbSetClient")
        self.buttonGroup.addButton(self.rbSetClient)
        self.horizontalLayout_7.addWidget(self.rbSetClient)
        self.lineServerAddr = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineServerAddr.setMinimumSize(QtCore.QSize(200, 30))
        self.lineServerAddr.setObjectName("lineServerAddr")
        self.horizontalLayout_7.addWidget(self.lineServerAddr)
        self.btnClientSwitch = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnClientSwitch.setMinimumSize(QtCore.QSize(90, 30))
        self.btnClientSwitch.setStyleSheet("font: 25 8pt \"Calibri Light\";")
        self.btnClientSwitch.setCheckable(True)
        self.btnClientSwitch.setObjectName("btnClientSwitch")
        self.horizontalLayout_7.addWidget(self.btnClientSwitch)
        self.lineClientCmd = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineClientCmd.setMinimumSize(QtCore.QSize(80, 30))
        self.lineClientCmd.setObjectName("lineClientCmd")
        self.horizontalLayout_7.addWidget(self.lineClientCmd)
        self.btnClientSend = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnClientSend.setMinimumSize(QtCore.QSize(90, 30))
        self.btnClientSend.setStyleSheet("font: 25 8pt \"Calibri Light\";")
        self.btnClientSend.setObjectName("btnClientSend")
        self.horizontalLayout_7.addWidget(self.btnClientSend)
        self.layoutWidget3 = QtWidgets.QWidget(self.GUI)
        self.layoutWidget3.setGeometry(QtCore.QRect(19, 173, 1011, 36))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbGenAll = QtWidgets.QCheckBox(self.layoutWidget3)
        self.cbGenAll.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.cbGenAll.setFont(font)
        self.cbGenAll.setChecked(False)
        self.cbGenAll.setObjectName("cbGenAll")
        self.horizontalLayout.addWidget(self.cbGenAll)
        self.btnGenSelect = QtWidgets.QPushButton(self.layoutWidget3)
        self.btnGenSelect.setMinimumSize(QtCore.QSize(120, 30))
        self.btnGenSelect.setCheckable(False)
        self.btnGenSelect.setObjectName("btnGenSelect")
        self.horizontalLayout.addWidget(self.btnGenSelect)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(628, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineGenCmd = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineGenCmd.setMinimumSize(QtCore.QSize(100, 30))
        self.lineGenCmd.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.lineGenCmd.setMaxLength(1)
        self.lineGenCmd.setObjectName("lineGenCmd")
        self.horizontalLayout_5.addWidget(self.lineGenCmd)
        self.btnGenSend = QtWidgets.QPushButton(self.layoutWidget3)
        self.btnGenSend.setMinimumSize(QtCore.QSize(80, 30))
        self.btnGenSend.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.btnGenSend.setFont(font)
        self.btnGenSend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGenSend.setObjectName("btnGenSend")
        self.horizontalLayout_5.addWidget(self.btnGenSend)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.tbCLLog.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_2.raise_()
        ezLNT.setCentralWidget(self.GUI)
        self.sb = QtWidgets.QStatusBar(ezLNT)
        self.sb.setObjectName("sb")
        ezLNT.setStatusBar(self.sb)
        self.mb = QtWidgets.QMenuBar(ezLNT)
        self.mb.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.mb.setObjectName("mb")
        self.menuMenu = QtWidgets.QMenu(self.mb)
        self.menuMenu.setStatusTip("")
        self.menuMenu.setWhatsThis("")
        self.menuMenu.setToolTipsVisible(True)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAbout = QtWidgets.QMenu(self.mb)
        self.menuAbout.setObjectName("menuAbout")
        ezLNT.setMenuBar(self.mb)
        self.actionRefresh = QtWidgets.QAction(ezLNT)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionExit = QtWidgets.QAction(ezLNT)
        self.actionExit.setObjectName("actionExit")
        self.actionVersion = QtWidgets.QAction(ezLNT)
        self.actionVersion.setObjectName("actionVersion")
        self.actionSoftware = QtWidgets.QAction(ezLNT)
        self.actionSoftware.setObjectName("actionSoftware")
        self.actionDumpPortInfo = QtWidgets.QAction(ezLNT)
        self.actionDumpPortInfo.setObjectName("actionDumpPortInfo")
        self.actionDumpLog = QtWidgets.QAction(ezLNT)
        self.actionDumpLog.setObjectName("actionDumpLog")
        self.actionDumpInfo = QtWidgets.QAction(ezLNT)
        self.actionDumpInfo.setObjectName("actionDumpInfo")
        self.menuMenu.addAction(self.actionRefresh)
        self.menuMenu.addAction(self.actionDumpInfo)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionVersion)
        self.menuAbout.addAction(self.actionSoftware)
        self.mb.addAction(self.menuMenu.menuAction())
        self.mb.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ezLNT)
        self.tw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ezLNT)

    def retranslateUi(self, ezLNT):
        _translate = QtCore.QCoreApplication.translate
        ezLNT.setWindowTitle(_translate("ezLNT", "Ports"))
        self.btnGenLog.setText(_translate("ezLNT", "Log"))
        self.btnGenClear.setText(_translate("ezLNT", "Clear"))
        self.zbShowInfo.setText(_translate("ezLNT", "Show Info"))
        self.zbToggle.setText(_translate("ezLNT", "Open Port"))
        self.zbRunScript.setText(_translate("ezLNT", "Run Script"))
        self.zbLoadConfig.setText(_translate("ezLNT", "Load Config"))
        self.zbSaveConfig.setText(_translate("ezLNT", "Save Config"))
        self.zbProgram.setText(_translate("ezLNT", "Program"))
        self.tw.setTabText(self.tw.indexOf(self.zigbee), _translate("ezLNT", "zigbee"))
        self.blmToggle.setText(_translate("ezLNT", "Open Port"))
        self.blmReset.setText(_translate("ezLNT", "Reset"))
        self.blmFN.setText(_translate("ezLNT", "FN"))
        self.blmRefresh.setText(_translate("ezLNT", "Refresh"))
        self.blmRunScpt.setText(_translate("ezLNT", "Run Script"))
        self.blmProgram.setText(_translate("ezLNT", "Program"))
        self.blmView.setText(_translate("ezLNT", "View"))
        self.tw.setTabText(self.tw.indexOf(self.ble_mesh), _translate("ezLNT", "ble mesh"))
        self.rbSetServer.setText(_translate("ezLNT", "Server"))
        self.btnServerSwitch.setText(_translate("ezLNT", "Setup"))
        self.cbTargetClientAddr.setItemText(0, _translate("ezLNT", "AllClients"))
        self.cbTargetClientAddr.setItemText(1, _translate("ezLNT", "SelectedPort"))
        self.btnServerSend.setText(_translate("ezLNT", "Send"))
        self.rbSetClient.setText(_translate("ezLNT", "Client"))
        self.btnClientSwitch.setText(_translate("ezLNT", "Connect"))
        self.btnClientSwitch.setShortcut(_translate("ezLNT", "Ctrl+Return"))
        self.btnClientSend.setText(_translate("ezLNT", "Send"))
        self.cbGenAll.setText(_translate("ezLNT", "All"))
        self.btnGenSelect.setText(_translate("ezLNT", "Select"))
        self.btnGenSend.setText(_translate("ezLNT", "Send"))
        self.menuMenu.setTitle(_translate("ezLNT", "Menu"))
        self.menuAbout.setTitle(_translate("ezLNT", "About"))
        self.actionRefresh.setText(_translate("ezLNT", "Refresh"))
        self.actionRefresh.setShortcut(_translate("ezLNT", "Ctrl+F"))
        self.actionExit.setText(_translate("ezLNT", "Exit"))
        self.actionExit.setShortcut(_translate("ezLNT", "Ctrl+Z"))
        self.actionVersion.setText(_translate("ezLNT", "Version"))
        self.actionSoftware.setText(_translate("ezLNT", "Software"))
        self.actionDumpPortInfo.setText(_translate("ezLNT", "Dump port info"))
        self.actionDumpLog.setText(_translate("ezLNT", "Dump Log"))
        self.actionDumpInfo.setText(_translate("ezLNT", "Dump Port Info"))
        self.actionDumpInfo.setShortcut(_translate("ezLNT", "Ctrl+P"))

