# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prgWin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 286)
        font = QtGui.QFont()
        font.setPointSize(7)
        Dialog.setFont(font)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 100, 182, 68))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbErsEPROM = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbErsEPROM.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.cbErsEPROM.setFont(font)
        self.cbErsEPROM.setStyleSheet("font: 25 10pt \"Calibri Light\";")
        self.cbErsEPROM.setObjectName("cbErsEPROM")
        self.verticalLayout.addWidget(self.cbErsEPROM)
        self.cbVrfy = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbVrfy.setMinimumSize(QtCore.QSize(180, 30))
        self.cbVrfy.setStyleSheet("font: 25 10pt \"Calibri Light\";")
        self.cbVrfy.setObjectName("cbVrfy")
        self.verticalLayout.addWidget(self.cbVrfy)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 41, 365, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbChsFl = QtWidgets.QLabel(self.layoutWidget)
        self.lbChsFl.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.lbChsFl.setFont(font)
        self.lbChsFl.setObjectName("lbChsFl")
        self.horizontalLayout.addWidget(self.lbChsFl)
        self.lineFl = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineFl.setMinimumSize(QtCore.QSize(200, 30))
        self.lineFl.setObjectName("lineFl")
        self.horizontalLayout.addWidget(self.lineFl)
        self.btnFlDlg = QtWidgets.QToolButton(self.layoutWidget)
        self.btnFlDlg.setMinimumSize(QtCore.QSize(30, 30))
        self.btnFlDlg.setObjectName("btnFlDlg")
        self.horizontalLayout.addWidget(self.btnFlDlg)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(190, 211, 208, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnProgram = QtWidgets.QPushButton(self.widget)
        self.btnProgram.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.btnProgram.setFont(font)
        self.btnProgram.setObjectName("btnProgram")
        self.horizontalLayout_2.addWidget(self.btnProgram)
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cbErsEPROM.setText(_translate("Dialog", "Erase EEPROM"))
        self.cbVrfy.setText(_translate("Dialog", "Verify"))
        self.lbChsFl.setText(_translate("Dialog", "Choose File :"))
        self.btnFlDlg.setText(_translate("Dialog", "..."))
        self.btnProgram.setText(_translate("Dialog", "Program"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))

